### PR TITLE
chore(gradle update): change compile to implementation

### PR DESCRIPTION
**Pull request by murageden**
Hey @vipulasri, fix your README. Are you still working on this? I wanted us to figure a way to make improvements on this. Specifically, having the strip show durations (events between two times) besides showing events at certain points in time.

### CODE REVIEW

**Comment by vipulasri** [comment]
@murageden Thanks for the pull request. Yeah, I am still working on improving this privately. 
Can you please explain your point "having the strip show durations (events between two times) besides showing events at certain points in time." ?

**Comment by murageden** [comment]
Let say you have an event say, for instance lunch between 1 and 2pm, and you want the timeline to have two oval drawables one at 1 and another at 2pm, such that the event is now in between the ovals and the marker becomes that line between.

**Comment by vipulasri** [comment]
Can you show me a screenshot/design of this?

**Comment by murageden** [comment]
Hi @vipulasri I hope this gives more context;

image

**Comment by vipulasri** [comment]
@murageden I understand your concern but I think it is not the actually the way library works. It needs to be continuous as of now. But I have a kind of hack for this you can use `setEndLine` and `setStartLine` methods and set their values as null. By which I think you will be able to get this view.

**Comment by murageden** [comment]
Ok. Thanks. I will look into that implementation

**Comment by vipulasri** [comment]
@murageden Thanks for the updated readme. But cant merge this as i re-writing the whole library.

**Comment by murageden** [comment]
Ok. You can put into consideration the above designs as you refactor the library.

**Comment by vipulasri** [comment]
@murageden sure. According to your use case. Did you made some changes? Love to know your approach in this rare case of yours.

**Comment by murageden** [comment]
No. Just pure designs. From scratch

**Comment by murageden** [comment]
No. Just pure designs. I didn't make use of your library. I designed from scratch

**Comment by murageden** [comment]
No. Just pure designs. I didn't make use of your library. I designed from scratch

**Comment by murageden** [comment]
No. These are pure designs, not borrowed from your library.

**Comment by murageden** [comment]
No. It was just pure designs from scratch

**Comment by murageden** [comment]
No. It was just pure designs from scratch

**Pull request closed without merging**
